### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by hillmich** [quingo/compiler_xtext#1]
Hi,

during some research on compilers, colleagues found your compiler. Many thanks making the source code public!

Please consider adding an explicit license to this code to enable people using it without worrying that they might get sued.
The [*quingo-runtime*](https://github.com/Quingo/Quingo-runtime/blob/master/LICENSE) is under the Apache-2.0 license, you could use the same license here.

Thank you!

**Comment by yjt98765** [comment]
Hi @hillmich, thank you for your kind and crucial suggestion! We have added an Apache-2.0 license, as you suggested. Thanks for your attention to Quingo. Cheers.
